'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language =
  | 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'mr' | 'bn' | 'bho'
  | 'gu' | 'pa' | 'or' | 'as' | 'ur' | 'ml' | 'mai' | 'sat'
  | 'kok' | 'doi' | 'ks' | 'mni' | 'ne' | 'sd' | 'sa';

export interface LanguageMeta {
  code: Language;
  name: string;
  native: string;
  flag: string;
}

export const LANGUAGES: LanguageMeta[] = [
  { code: 'en',  name: 'English',   flag: '🇬🇧', native: 'English'   },
  { code: 'hi',  name: 'Hindi',     flag: '🇮🇳', native: 'हिंदी'     },
  { code: 'te',  name: 'Telugu',    flag: '🇮🇳', native: 'తెలుగు'    },
  { code: 'ta',  name: 'Tamil',     flag: '🇮🇳', native: 'தமிழ்'     },
  { code: 'kn',  name: 'Kannada',   flag: '🇮🇳', native: 'ಕನ್ನಡ'    },
  { code: 'mr',  name: 'Marathi',   flag: '🇮🇳', native: 'मराठी'     },
  { code: 'bn',  name: 'Bengali',   flag: '🇮🇳', native: 'বাংলা'     },
  { code: 'bho', name: 'Bhojpuri',  flag: '🇮🇳', native: 'भोजपुरी'   },
  { code: 'gu',  name: 'Gujarati',  flag: '🇮🇳', native: 'ગુજરાતી'  },
  { code: 'pa',  name: 'Punjabi',   flag: '🇮🇳', native: 'ਪੰਜਾਬੀ'    },
  { code: 'or',  name: 'Odia',      flag: '🇮🇳', native: 'ଓଡ଼ିଆ'      },
  { code: 'as',  name: 'Assamese',  flag: '🇮🇳', native: 'অসমীয়া'   },
  { code: 'ur',  name: 'Urdu',      flag: '🇮🇳', native: 'اردو'      },
  { code: 'ml',  name: 'Malayalam', flag: '🇮🇳', native: 'മലയാളം'   },
  { code: 'mai', name: 'Maithili',  flag: '🇮🇳', native: 'मैथिली'    },
  { code: 'sat', name: 'Santali',   flag: '🇮🇳', native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'kok', name: 'Konkani',   flag: '🇮🇳', native: 'कोंकणी'    },
  { code: 'doi', name: 'Dogri',     flag: '🇮🇳', native: 'डोगरी'     },
  { code: 'ks',  name: 'Kashmiri',  flag: '🇮🇳', native: 'کٲشُر'     },
  { code: 'mni', name: 'Manipuri',  flag: '🇮🇳', native: 'মেইতেই'   },
  { code: 'ne',  name: 'Nepali',    flag: '🇳🇵', native: 'नेपाली'    },
  { code: 'sd',  name: 'Sindhi',    flag: '🇮🇳', native: 'سنڌي'     },
  { code: 'sa',  name: 'Sanskrit',  flag: '🇮🇳', native: 'संस्कृतम्' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLangMeta: LanguageMeta;
  getLanguageInstruction: () => string;
}

// ─── TRANSLATIONS ───────────────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav & Dashboard
    dashboard: 'Dashboard',
    askAIDoctor: 'Ask AI Doctor',
    symptomChecker: 'Symptom Checker',
    medicineFinder: 'Medicine Finder',
    medicineScanner: 'Medicine Scanner',
    medicalReports: 'Medical Reports',
    healthTracker: 'Health Tracker',
    appointments: 'Appointments',
    emergency: 'Emergency',
    hospitals: 'Hospitals',
    settings: 'Settings',
    searchPlaceholder: 'Ask about symptoms, medicines, diseases...',
    onlineDoctor: 'Online Doctor',
    nearbyHospitals: 'Nearby Hospitals',
    viewAll: 'View All',
    selectLocation: 'Select Location',
    medicineInfo: 'Medicine Info',
    scanMedicine: 'Scan Medicine',
    scanDescription: 'Scan any medicine to get complete details instantly',
    aiDiagnosis: 'AI Diagnosis Suggestion',
    healthStats: 'Health Stats',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    sugarLevel: 'Sugar Level',
    enterSymptoms: 'Enter your symptoms below',
    aiSuggestion: 'AI Suggestion',
    possibleViral: 'Possible Viral Infection',
    condition: 'Possible Condition',
    openFull: 'Open Full Checker',
    usedFor: 'Used for',
    dosage: 'Dosage',
    availability: 'Availability',
    healthPredictors: 'Health Predictors',

    // Medical Profile
    medicalProfile: 'Medical Profile',
    myMedicalProfile: 'My Medical Profile',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    age: 'Age',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    medicalConditions: 'Medical Conditions',
    currentMedications: 'Current Medications',
    allergies: 'Allergies',
    vitals: 'Vitals',
    emergencyContact: 'Emergency Contact',
    preferredHospitals: 'Preferred Hospitals',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile Saved!',
    saving: 'Saving…',
    privateData: 'Private — only visible to you',
    profileAutoFills: 'Profile saved — auto-fills your SOS alerts',
    completeProfile: 'Complete your Medical Profile',
    organDonor: 'I am an Organ Donor',
    doctorNotes: 'Special Notes for Doctors',
    insurance: 'Insurance',
    hasInsurance: 'I have health insurance',
    policyNumber: 'Policy Number',

    // Settings
    profilePicture: 'Profile Picture',
    uploadPhoto: 'Upload Photo',
    displayName: 'Display Name',
    email: 'Email',
    bio: 'Bio',
    saveChanges: 'Save Changes',
    appearance: 'Appearance',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    notifications: 'Notifications',
    privacy: 'Privacy',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account & Data',

    // SOS / Crisis
    emergency_title: 'Emergency?',
    emergency_subtitle: 'Instant help is one tap away. Press the button to alert hotel staff immediately.',
    reportEmergency: 'Report Emergency',
    yourName: 'Your Name',
    roomNo: 'Room No.',
    floor: 'Floor',
    emergencyType: 'Emergency Type',
    describeEmergency: 'Describe the Emergency',
    sendAlert: 'Send Emergency Alert',
    alertCreated: 'Alert Created',
    helpDispatched: 'Help is being dispatched',
    medicalProfileLoaded: 'Medical Profile Auto-Loaded',
    noProfileFound: 'No medical profile found.',
    setOneUp: 'Set one up',
    fasterCare: 'for faster emergency care.',
    profileSentToHospital: 'This data will be sent to hotel staff and the hospital automatically.',

    // Hospital Portal
    hospitalPortal: 'Hospital Emergency Portal',
    incomingPatients: 'Incoming Patients',
    acknowledgeAlert: 'Acknowledge Alert',
    bedReady: 'Bed Ready',
    patientArrived: 'Patient Arrived',
    assignBed: 'Assign Bed',
    assignResponder: 'Assign Responder',
    noIncomingAlerts: 'No incoming patient alerts',
    icdCode: 'ICD-10 Code',
    condition_label: 'Condition',
    department: 'Department',
    bloodType: 'Blood Type',
    knownConditions: 'Known Conditions',
    medications: 'Medications',
    preferredHospital: 'Preferred Hospital',

    // Auth
    welcomeBack: 'Welcome Back',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    continueWithGoogle: 'Continue with Google',
    or: 'or',

    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    refresh: 'Refresh',
    connected: 'Connected',
    connecting: 'Connecting...',
    error: 'Error',
    success: 'Success',

    // Symptom Checker
    symptomCheckerTitle: 'Symptom Checker',
    symptomCheckerSubtitle: 'AI-powered medicine recommendations based on your profile',
    patientProfile: 'Patient Profile',
    selectSymptoms: 'Select Symptoms',
    searchSymptoms: 'Search symptoms…',
    addOtherSymptom: 'Add other symptom…',
    add: 'Add',
    analyzeSymptoms: 'Analyze Symptoms',
    analyzingAI: 'Analyzing with AI…',
    aiMedicineRecommendations: 'AI Medicine Recommendations',
    fillProfilePrompt: 'Fill in your patient profile and select your symptoms, then click "Analyze Symptoms" to get AI-powered medicine recommendations.',
    analyzingYourSymptoms: 'Analyzing your symptoms…',
    aiReviewingProfile: 'Our AI is reviewing your profile and finding the best medicines',
    aiDiagnosisTitle: 'AI Diagnosis',
    basedOnSymptoms: 'Based on your symptoms & profile',
    recommendedMedicines: 'Recommended Medicines',
    generalAdvice: 'General Advice',
    whenToSeeDoctor: 'When to See a Doctor',
    disclaimerText: 'This is AI-generated advice. Always consult a qualified doctor.',
    disclaimerBanner: 'This is AI-generated advice for informational purposes only. Always consult a qualified doctor before taking any medicine.',
    bookMedicine: 'Book This Medicine',
    bookTest: 'Book Test',
    diabetic: 'Diabetic?',
    pregnant: 'Pregnant?',

    // Medicine Scanner
    scannerTitle: 'Medicine Scanner',
    scannerSubtitle: 'Point your camera at any medicine to get instant AI analysis',
    takePhoto: 'Take Photo',
    uploadImage: 'Upload Image',
    analyzing: 'Analyzing…',
    composition: 'Composition',
    sideEffects: 'Side Effects',
    warnings: 'Warnings',
    alternatives: 'Alternatives',
    prescriptionRequired: 'Prescription Required',
    overTheCounter: 'Over the Counter',

    // Ask AI Doctor
    askAIDoctorTitle: 'Arogya AI',
    typingStatus: 'Typing…',
    alwaysOnline: 'Always online • Powered by Groq AI',
    clearChat: 'Clear',
    today: 'Today',
    thinking: 'Thinking…',
    askPlaceholder: 'Describe your symptoms or ask a medical question...',
    aiDisclaimer: 'Powered by Groq AI • Arogya AI can make mistakes. Consider verifying important information with a doctor.',

    // Hospitals
    hospitalsTitle: 'Nearby Hospitals',
    findHospitals: 'Find Hospitals',
    distance: 'Distance',
    openNow: 'Open Now',
    closed: 'Closed',
    departments: 'Departments',
    getDirections: 'Get Directions',
    call: 'Call',
    bookAppointment: 'Book Appointment',
    appointmentBooked: 'Appointment Booked Successfully!',
    appointmentBookedMsg: 'Your appointment has been booked. You will receive a confirmation shortly.',
    patientName: 'Patient Name',
    phoneNumber: 'Phone Number',
    specialty: 'Specialty',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    reasonForVisit: 'Reason for Visit',
    confirmBooking: 'Confirm Booking',

    // Health Predictors
    predictorsTitle: 'Health Risk Predictors',
    predictorsSubtitle: 'AI-powered disease risk assessment based on medical data',
    riskScore: 'Risk Score',
    riskLevel: 'Risk Level',
    riskFactors: 'Risk Factors',
    runPredictor: 'Run Predictor',
    lowRisk: 'Low Risk',
    moderateRisk: 'Moderate Risk',
    highRisk: 'High Risk',
    veryHighRisk: 'Very High Risk',
    enterHealthData: 'Enter your health data to get personalized risk assessment',

    // Analytics
    analyticsTitle: 'Health Analytics',
    analyticsSubtitle: 'Track your health trends and insights',
    overview: 'Overview',
    trends: 'Trends',
    insights: 'Insights',

    // Crisis
    crisisTitle: 'Crisis Response Center',
    reportCrisis: 'Report Crisis',
    responder: 'Responder',
    status: 'Status',
    location: 'Location',

    // Media
    mediaTitle: 'Health Media Gallery',
    upload: 'Upload',
    myUploads: 'My Uploads',
    delete: 'Delete',
    preview: 'Preview',

    // Common Feature Labels
    poweredByAI: 'Powered by AI',
    noResults: 'No results found',
    tryAgain: 'Try again',
    selectAtLeastOne: 'Please select at least one',
    enterAge: 'Please enter your age',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    select: 'Select',
    frequency: 'Frequency',
    duration: 'Duration',
    timing: 'Timing',
    purpose: 'Purpose',
    quizTitle: 'AI Health Quiz',
    quizSubtitle: 'Ask AI to generate a quiz on any health topic',
    generateQuiz: 'Generate Quiz',
    generating: 'Generating...',
    startQuiz: 'Start Quiz',
    nextQuestion: 'Next Question',
    viewResults: 'View Results',
    retryQuiz: 'Retry Quiz',
    allCategories: 'All Categories',
    correct: 'Correct',
    wrong: 'Wrong',
    accuracy: 'Accuracy',
    explanation: 'Explanation',
    questionBreakdown: 'Question Breakdown',
    orPickCategory: 'OR PICK A CATEGORY',
    generateWithAI: 'Generate Quiz with AI',
    aiGeneratingQuiz: 'AI is crafting your quiz questions...',
    medicineName: 'Medicine Name',
    searchMedicine: 'Search medicines',
    price: 'Price',
    manufacturer: 'Manufacturer',
    type: 'Type',
    uses: 'Uses',
    diagnosticCentre: 'Diagnostic Centre',
    bookNow: 'Book Now',
    doctors: 'Doctors',
    findDoctors: 'Find Doctors',
    videoCall: 'Video Call',
    reports: 'Reports',
    healthcareNavigator: 'Healthcare Navigator',
    navigating: 'Navigating to',
    disclaimerText: 'Always consult a licensed doctor before taking any medication.',
    confirmBooking: 'Confirm Booking',
    cancel: 'Cancel',
    medicalProfile: 'Medical Profile',
    patientName: 'Your name',
    specialty: 'Select Specialty',
    reasonForVisit: 'Reason for visit',
    predictorsTitle: 'Health Predictors',
    predictorsSubtitle: 'Get personalized health risk assessments powered by real medical datasets.',
    analyticsTitle: 'Health Analytics',
    poweredByAI: 'Powered by Groq AI',
    bookAppointment: 'Book Appointment',
  },

  hi: {
    dashboard: 'डैशबोर्ड',
    askAIDoctor: 'AI डॉक्टर से पूछें',
    symptomChecker: 'लक्षण जाँचक',
    medicineFinder: 'दवा खोजक',
    medicineScanner: 'दवा स्कैनर',
    medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर',
    appointments: 'अपॉइंटमेंट',
    emergency: 'आपातकालीन',
    hospitals: 'अस्पताल',
    settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षणों, दवाओं, रोगों के बारे में पूछें...',
    onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'पास के अस्पताल',
    viewAll: 'सभी देखें',
    selectLocation: 'स्थान चुनें',
    medicineInfo: 'दवा की जानकारी',
    scanMedicine: 'दवा स्कैन करें',
    scanDescription: 'किसी भी दवा को तुरंत स्कैन करें और विवरण प्राप्त करें',
    aiDiagnosis: 'AI निदान सुझाव',
    healthStats: 'स्वास्थ्य आँकड़े',
    heartRate: 'हृदय गति',
    bloodPressure: 'रक्तचाप',
    sugarLevel: 'शुगर लेवल',
    enterSymptoms: 'नीचे अपने लक्षण दर्ज करें',
    aiSuggestion: 'AI सुझाव',
    possibleViral: 'संभावित वायरल संक्रमण',
    condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलें',
    usedFor: 'के लिए उपयोग किया जाता है',
    dosage: 'खुराक',
    availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
    medicalProfile: 'मेडिकल प्रोफ़ाइल',
    myMedicalProfile: 'मेरी मेडिकल प्रोफ़ाइल',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    age: 'आयु',
    dateOfBirth: 'जन्म तिथि',
    gender: 'लिंग',
    bloodGroup: 'रक्त समूह',
    height: 'ऊँचाई (सेमी)',
    weight: 'वज़न (किग्रा)',
    medicalConditions: 'चिकित्सा स्थितियाँ',
    currentMedications: 'वर्तमान दवाएँ',
    allergies: 'एलर्जी',
    vitals: 'महत्वपूर्ण संकेत',
    emergencyContact: 'आपातकालीन संपर्क',
    preferredHospitals: 'पसंदीदा अस्पताल',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    profileSaved: 'प्रोफ़ाइल सहेजी गई!',
    saving: 'सहेजा जा रहा है…',
    privateData: 'निजी — केवल आपको दिखता है',
    profileAutoFills: 'प्रोफ़ाइल सहेजी — SOS अलर्ट में स्वतः भरती है',
    completeProfile: 'अपनी मेडिकल प्रोफ़ाइल पूरी करें',
    organDonor: 'मैं अंग दाता हूँ',
    doctorNotes: 'डॉक्टरों के लिए विशेष नोट्स',
    insurance: 'बीमा',
    hasInsurance: 'मेरे पास स्वास्थ्य बीमा है',
    policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफ़ाइल तस्वीर',
    uploadPhoto: 'तस्वीर अपलोड करें',
    displayName: 'प्रदर्शन नाम',
    email: 'ईमेल',
    bio: 'परिचय',
    saveChanges: 'परिवर्तन सहेजें',
    appearance: 'दिखावट',
    lightMode: 'लाइट',
    darkMode: 'डार्क',
    systemMode: 'सिस्टम',
    notifications: 'सूचनाएँ',
    privacy: 'गोपनीयता',
    signOut: 'साइन आउट',
    deleteAccount: 'खाता और डेटा हटाएँ',
    emergency_title: 'आपातकाल?',
    emergency_subtitle: 'तत्काल सहायता एक टैप दूर है। होटल स्टाफ को तुरंत सतर्क करने के लिए बटन दबाएँ।',
    reportEmergency: 'आपातकाल की रिपोर्ट करें',
    yourName: 'आपका नाम',
    roomNo: 'कमरा नंबर',
    floor: 'मंज़िल',
    emergencyType: 'आपातकाल का प्रकार',
    describeEmergency: 'आपातकाल का वर्णन करें',
    sendAlert: 'आपातकाल अलर्ट भेजें',
    alertCreated: 'अलर्ट बना दिया गया',
    helpDispatched: 'सहायता भेजी जा रही है',
    medicalProfileLoaded: 'मेडिकल प्रोफ़ाइल स्वतः लोड हुई',
    noProfileFound: 'कोई मेडिकल प्रोफ़ाइल नहीं मिली।',
    setOneUp: 'अभी बनाएँ',
    fasterCare: 'तेज़ आपातकालीन देखभाल के लिए।',
    profileSentToHospital: 'यह डेटा होटल स्टाफ और अस्पताल को स्वचालित रूप से भेजा जाएगा।',
    hospitalPortal: 'अस्पताल आपातकाल पोर्टल',
    incomingPatients: 'आने वाले मरीज़',
    acknowledgeAlert: 'अलर्ट स्वीकार करें',
    bedReady: 'बिस्तर तैयार',
    patientArrived: 'मरीज़ पहुँच गया',
    assignBed: 'बिस्तर आवंटित करें',
    assignResponder: 'रेस्पॉंडर नियुक्त करें',
    noIncomingAlerts: 'कोई आने वाले मरीज़ अलर्ट नहीं',
    icdCode: 'ICD-10 कोड',
    condition_label: 'स्थिति',
    department: 'विभाग',
    bloodType: 'रक्त प्रकार',
    knownConditions: 'ज्ञात स्थितियाँ',
    medications: 'दवाएँ',
    preferredHospital: 'पसंदीदा अस्पताल',
    welcomeBack: 'वापसी पर स्वागत है',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    continueWithGoogle: 'Google से जारी रखें',
    or: 'या',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'अगला',
    submit: 'सबमिट करें',
    refresh: 'रिफ्रेश करें',
    connected: 'कनेक्टेड',
    connecting: 'कनेक्ट हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    symptomCheckerTitle: 'लक्षण जाँचक',
    symptomCheckerSubtitle: 'आपकी प्रोफ़ाइल के आधार पर AI दवा सिफारिशें',
    patientProfile: 'रोगी प्रोफ़ाइल',
    selectSymptoms: 'लक्षण चुनें',
    searchSymptoms: 'लक्षण खोजें…',
    addOtherSymptom: 'अन्य लक्षण जोड़ें…',
    add: 'जोड़ें',
    analyzeSymptoms: 'लक्षण विश्लेषण करें',
    analyzingAI: 'AI से विश्लेषण हो रहा है…',
    aiMedicineRecommendations: 'AI दवा सिफारिशें',
    fillProfilePrompt: 'अपनी रोगी प्रोफ़ाइल भरें और लक्षण चुनें, फिर AI दवा सिफारिशें पाने के लिए "लक्षण विश्लेषण" पर क्लिक करें।',
    analyzingYourSymptoms: 'आपके लक्षणों का विश्लेषण हो रहा है…',
    aiReviewingProfile: 'हमारा AI आपकी प्रोफ़ाइल की समीक्षा कर रहा है',
    aiDiagnosisTitle: 'AI निदान',
    basedOnSymptoms: 'आपके लक्षणों और प्रोफ़ाइल के आधार पर',
    recommendedMedicines: 'सुझाई गई दवाएँ',
    generalAdvice: 'सामान्य सलाह',
    whenToSeeDoctor: 'डॉक्टर को कब दिखाएं',
    disclaimerText: 'यह AI-जनित सलाह है। हमेशा योग्य चिकित्सक से परामर्श लें।',
    disclaimerBanner: 'यह केवल जानकारी के लिए AI-जनित सलाह है। कोई भी दवा लेने से पहले हमेशा योग्य चिकित्सक से परामर्श लें।',
    bookMedicine: 'यह दवा बुक करें',
    bookTest: 'टेस्ट बुक करें',
    diabetic: 'मधुमेह?',
    pregnant: 'गर्भवती?',
    scannerTitle: 'दवा स्कैनर',
    scannerSubtitle: 'तत्काल AI विश्लेषण के लिए किसी भी दवा पर कैमरा करें',
    takePhoto: 'फोटो लें',
    uploadImage: 'छवि अपलोड करें',
    analyzing: 'विश्लेषण हो रहा है…',
    composition: 'संरचना',
    sideEffects: 'दुष्प्रभाव',
    warnings: 'चेतावनियाँ',
    alternatives: 'विकल्प',
    prescriptionRequired: 'प्रिस्क्रिप्शन आवश्यक',
    overTheCounter: 'बिना प्रिस्क्रिप्शन',
    askAIDoctorTitle: 'आरोग्य AI',
    typingStatus: 'टाइप कर रहा है…',
    alwaysOnline: 'हमेशा ऑनलाइन • Groq AI द्वारा संचालित',
    clearChat: 'साफ करें',
    today: 'आज',
    thinking: 'सोच रहा है…',
    askPlaceholder: 'अपने लक्षण बताएं या कोई चिकित्सा प्रश्न पूछें...',
    aiDisclaimer: 'Groq AI द्वारा संचालित • आरोग्य AI गलतियाँ कर सकता है। डॉक्टर से महत्वपूर्ण जानकारी सत्यापित करें।',
    hospitalsTitle: 'पास के अस्पताल',
    findHospitals: 'अस्पताल खोजें',
    distance: 'दूरी',
    openNow: 'अभी खुला है',
    closed: 'बंद',
    departments: 'विभाग',
    getDirections: 'दिशा-निर्देश पाएं',
    call: 'कॉल करें',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    appointmentBooked: 'अपॉइंटमेंट सफलतापूर्वक बुक हो गई!',
    appointmentBookedMsg: 'आपकी अपॉइंटमेंट बुक हो गई है। आपको जल्द ही पुष्टि मिलेगी।',
    patientName: 'रोगी का नाम',
    phoneNumber: 'फोन नंबर',
    specialty: 'विशेषज्ञता',
    selectDate: 'तारीख चुनें',
    selectTime: 'समय चुनें',
    reasonForVisit: 'मिलने का कारण',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    predictorsTitle: 'स्वास्थ्य जोखिम भविष्यवक्ता',
    predictorsSubtitle: 'चिकित्सा डेटा पर आधारित AI रोग जोखिम मूल्यांकन',
    riskScore: 'जोखिम स्कोर',
    riskLevel: 'जोखिम स्तर',
    riskFactors: 'जोखिम कारक',
    runPredictor: 'भविष्यवक्ता चलाएं',
    lowRisk: 'कम जोखिम',
    moderateRisk: 'मध्यम जोखिम',
    highRisk: 'उच्च जोखिम',
    veryHighRisk: 'बहुत उच्च जोखिम',
    enterHealthData: 'व्यक्तिगत जोखिम मूल्यांकन के लिए स्वास्थ्य डेटा दर्ज करें',
    analyticsTitle: 'स्वास्थ्य विश्लेषण',
    analyticsSubtitle: 'अपने स्वास्थ्य रुझानों को ट्रैक करें',
    overview: 'अवलोकन',
    trends: 'रुझान',
    insights: 'अंतर्दृष्टि',
    crisisTitle: 'संकट प्रतिक्रिया केंद्र',
    reportCrisis: 'संकट की रिपोर्ट करें',
    responder: 'प्रतिक्रियाकर्ता',
    status: 'स्थिति',
    location: 'स्थान',
    mediaTitle: 'स्वास्थ्य मीडिया गैलरी',
    upload: 'अपलोड',
    myUploads: 'मेरे अपलोड',
    delete: 'हटाएं',
    preview: 'पूर्वावलोकन',
    poweredByAI: 'AI द्वारा संचालित',
    noResults: 'कोई परिणाम नहीं मिला',
    tryAgain: 'फिर से कोशिश करें',
    selectAtLeastOne: 'कृपया कम से कम एक चुनें',
    enterAge: 'कृपया अपनी आयु दर्ज करें',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    select: 'चुनें',
    frequency: 'आवृत्ति',
    duration: 'अवधि',
    timing: 'समय',
    purpose: 'उद्देश्य',
    quizTitle: 'AI स्वास्थ्य क्विज़',
    quizSubtitle: 'किसी भी स्वास्थ्य विषय पर AI क्विज़',
    generateQuiz: 'क्विज़ बनाएं',
    generating: 'बना रहा है...',
    startQuiz: 'क्विज़ शुरू करें',
    nextQuestion: 'अगला प्रश्न',
    viewResults: 'परिणाम देखें',
    retryQuiz: 'फिर से प्रयास करें',
    allCategories: 'सभी श्रेणियां',
    correct: 'सही',
    wrong: 'गलत',
    accuracy: 'सटीकता',
    explanation: 'स्पष्टीकरण',
    questionBreakdown: 'प्रश्न विश्लेषण',
    orPickCategory: 'या एक श्रेणी चुनें',
    generateWithAI: 'AI से क्विज़ बनाएं',
    aiGeneratingQuiz: 'AI आपके क्विज़ प्रश्न बना रहा है...',
    medicineName: 'दवा का नाम',
    searchMedicine: 'दवा खोजें',
    price: 'मूल्य',
    manufacturer: 'निर्माता',
    type: 'प्रकार',
    uses: 'उपयोग',
    diagnosticCentre: 'डायग्नोस्टिक सेंटर',
    bookNow: 'अभी बुक करें',
    doctors: 'डॉक्टर',
    findDoctors: 'डॉक्टर खोजें',
    videoCall: 'वीडियो कॉल',
    reports: 'रिपोर्ट',
    healthcareNavigator: 'हेल्थकेयर नेविगेटर',
    navigating: 'नेविगेट कर रहे हैं',
    disclaimerText: 'कोई भी दवा लेने से पहले हमेशा लाइसेंस प्राप्त डॉक्टर से सलाह लें।',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    cancel: 'रद्द करें',
    medicalProfile: 'मेडिकल प्रोफाइल',
    patientName: 'आपका नाम',
    specialty: 'विशेषज्ञता चुनें',
    reasonForVisit: 'मिलने का कारण',
    predictorsTitle: 'स्वास्थ्य भविष्यवक्ता',
    predictorsSubtitle: 'वास्तविक चिकित्सा डेटासेट द्वारा संचालित व्यक्तिगत स्वास्थ्य जोखिम मूल्यांकन प्राप्त करें।',
    analyticsTitle: 'स्वास्थ्य विश्लेषण',
    poweredByAI: 'AI द्वारा संचालित',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
  },

  te: {
    dashboard: 'డాష్‌బోర్డ్',
    askAIDoctor: 'AI డాక్టర్‌ని అడగండి',
    symptomChecker: 'లక్షణాల తనిఖీ',
    medicineFinder: 'మందుల అన్వేషణ',
    medicineScanner: 'మందుల స్కానర్',
    medicalReports: 'వైద్య నివేదికలు',
    healthTracker: 'ఆరోగ్య ట్రాకర్',
    appointments: 'అపాయింట్‌మెంట్‌లు',
    emergency: 'అత్యవసర',
    hospitals: 'ఆసుపత్రులు',
    settings: 'సెట్టింగ్‌లు',
    searchPlaceholder: 'లక్షణాలు, మందులు, వ్యాధుల గురించి అడగండి...',
    onlineDoctor: 'ఆన్‌లైన్ డాక్టర్',
    nearbyHospitals: 'సమీప ఆసుపత్రులు',
    viewAll: 'అన్నీ చూడు',
    selectLocation: 'స్థానాన్ని ఎంచుకోండి',
    medicineInfo: 'మందుల సమాచారం',
    scanMedicine: 'మెడిసిన్ స్కాన్ చేయండి',
    scanDescription: 'ఏదైనా మందుని తక్షణమే స్కాన్ చేసి వివరాలు పొందండి',
    aiDiagnosis: 'AI రోగనిర్ధారణ సూచన',
    healthStats: 'ఆరోగ్య గణాంకాలు',
    heartRate: 'గుండె వేగం',
    bloodPressure: 'రక్తపోటు',
    sugarLevel: 'షుగర్ లెవల్',
    enterSymptoms: 'మీ లక్షణాలను క్రింద నమోదు చేయండి',
    aiSuggestion: 'AI సూచన',
    possibleViral: 'వైరల్ ఇన్ఫెక్షన్ కావచ్చు',
    condition: 'సాధ్యమైన పరిస్థితి',
    openFull: 'పూర్తి తనిఖీని తెరవండి',
    usedFor: 'కోసం ఉపయోగించబడుతుంది',
    dosage: 'మోతాదు',
    availability: 'అందుబాటులో ఉంది',
    healthPredictors: 'ఆరోగ్య అంచనాలు',
    medicalProfile: 'వైద్య ప్రొఫైల్',
    myMedicalProfile: 'నా వైద్య ప్రొఫైల్',
    personalInfo: 'వ్యక్తిగత సమాచారం',
    fullName: 'పూర్తి పేరు',
    age: 'వయసు',
    dateOfBirth: 'పుట్టిన తేదీ',
    gender: 'లింగం',
    bloodGroup: 'రక్త సమూహం',
    height: 'ఎత్తు (సెమీ)',
    weight: 'బరువు (కేజీ)',
    medicalConditions: 'వైద్య పరిస్థితులు',
    currentMedications: 'ప్రస్తుత మందులు',
    allergies: 'అలెర్జీలు',
    vitals: 'జీవ సంకేతాలు',
    emergencyContact: 'అత్యవసర సంప్రదింపు',
    preferredHospitals: 'ఇష్టమైన ఆసుపత్రులు',
    saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
    profileSaved: 'ప్రొఫైల్ సేవ్ అయింది!',
    saving: 'సేవ్ అవుతోంది…',
    privateData: 'ప్రైవేట్ — మీకు మాత్రమే కనిపిస్తుంది',
    profileAutoFills: 'ప్రొఫైల్ సేవ్ అయింది — SOS అప్రమత్తాలలో స్వయంచాలిత నింపడం',
    completeProfile: 'మీ వైద్య ప్రొఫైల్‌ను పూర్తి చేయండి',
    organDonor: 'నేను అవయవ దాత',
    doctorNotes: 'వైద్యులకు ప్రత్యేక గమనికలు',
    insurance: 'బీమా',
    hasInsurance: 'నాకు ఆరోగ్య బీమా ఉంది',
    policyNumber: 'పాలసీ నంబర్',
    profilePicture: 'ప్రొఫైల్ చిత్రం',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
    displayName: 'ప్రదర్శన పేరు',
    email: 'ఇమెయిల్',
    bio: 'పరిచయం',
    saveChanges: 'మార్పులు సేవ్ చేయండి',
    appearance: 'రూపం',
    lightMode: 'లైట్',
    darkMode: 'డార్క్',
    systemMode: 'సిస్టమ్',
    notifications: 'నోటిఫికేషన్లు',
    privacy: 'గోప్యత',
    signOut: 'సైన్ అవుట్',
    deleteAccount: 'ఖాతా మరియు డేటా తొలగించండి',
    emergency_title: 'అత్యవసరం?',
    emergency_subtitle: 'తక్షణ సహాయం ఒక్క నొక్కు దూరంలో ఉంది. హోటల్ సిబ్బందిని వెంటనే హెచ్చరించడానికి బటన్ నొక్కండి.',
    reportEmergency: 'అత్యవసరం నివేదించండి',
    yourName: 'మీ పేరు',
    roomNo: 'గది నంబర్',
    floor: 'అంతస్తు',
    emergencyType: 'అత్యవసర రకం',
    describeEmergency: 'అత్యవసరాన్ని వివరించండి',
    sendAlert: 'అత్యవసర హెచ్చరిక పంపండి',
    alertCreated: 'హెచ్చరిక సృష్టించబడింది',
    helpDispatched: 'సహాయం పంపబడుతోంది',
    medicalProfileLoaded: 'వైద్య ప్రొఫైల్ స్వయంచాలితంగా లోడ్ అయింది',
    noProfileFound: 'వైద్య ప్రొఫైల్ కనుగొనబడలేదు.',
    setOneUp: 'ఒకటి సెటప్ చేయండి',
    fasterCare: 'వేగవంతమైన అత్యవసర సంరక్షణ కోసం.',
    profileSentToHospital: 'ఈ డేటా హోటల్ సిబ్బంది మరియు ఆసుపత్రికి స్వయంచాలితంగా పంపబడుతుంది.',
    hospitalPortal: 'ఆసుపత్రి అత్యవసర పోర్టల్',
    incomingPatients: 'వచ్చే రోగులు',
    acknowledgeAlert: 'హెచ్చరికను ధృవీకరించండి',
    bedReady: 'మంచం సిద్ధంగా ఉంది',
    patientArrived: 'రోగి వచ్చాడు',
    assignBed: 'మంచం కేటాయించండి',
    assignResponder: 'రెస్పాండర్‌ను నియమించండి',
    noIncomingAlerts: 'ఇన్‌కమింగ్ పేషెంట్ అలర్ట్‌లు లేవు',
    icdCode: 'ICD-10 కోడ్',
    condition_label: 'పరిస్థితి',
    department: 'విభాగం',
    bloodType: 'రక్త రకం',
    knownConditions: 'తెలిసిన పరిస్థితులు',
    medications: 'మందులు',
    preferredHospital: 'ఇష్టమైన ఆసుపత్రి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    continueWithGoogle: 'Google తో కొనసాగించు',
    or: 'లేదా',
    loading: 'లోడ్ అవుతోంది...',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    close: 'మూసివేయండి',
    back: 'వెనుకకు',
    next: 'తదుపరి',
    submit: 'సబ్మిట్ చేయండి',
    refresh: 'రిఫ్రెష్ చేయండి',
    connected: 'కనెక్ట్ అయింది',
    connecting: 'కనెక్ట్ అవుతోంది...',
    error: 'లోపం',
    success: 'విజయం',
    symptomCheckerTitle: 'లక్షణాల తనిఖీ',
    symptomCheckerSubtitle: 'మీ ప్రొఫైల్ ఆధారంగా AI మందుల సిఫారసులు',
    patientProfile: 'రోగి ప్రొఫైల్',
    selectSymptoms: 'లక్షణాలను ఎంచుకోండి',
    searchSymptoms: 'లక్షణాలు వెతకండి…',
    addOtherSymptom: 'ఇతర లక్షణం జోడించండి…',
    add: 'జోడించు',
    analyzeSymptoms: 'లక్షణాలను విశ్లేషించండి',
    analyzingAI: 'AI తో విశ్లేషిస్తోంది…',
    aiMedicineRecommendations: 'AI మందుల సిఫారసులు',
    fillProfilePrompt: 'మీ రోగి ప్రొఫైల్ నింపండి మరియు లక్షణాలను ఎంచుకోండి.',
    analyzingYourSymptoms: 'మీ లక్షణాలను విశ్లేషిస్తోంది…',
    aiReviewingProfile: 'మా AI మీ ప్రొఫైల్‌ను సమీక్షిస్తోంది',
    aiDiagnosisTitle: 'AI రోగనిర్ధారణ',
    basedOnSymptoms: 'మీ లక్షణాలు & ప్రొఫైల్ ఆధారంగా',
    recommendedMedicines: 'సిఫారసు చేసిన మందులు',
    generalAdvice: 'సాధారణ సలహా',
    whenToSeeDoctor: 'డాక్టర్‌ని ఎప్పుడు చూడాలి',
    disclaimerText: 'ఇది AI-సృష్టించిన సలహా. ఎల్లప్పుడూ అర్హత గల వైద్యుడిని సంప్రదించండి.',
    disclaimerBanner: 'ఇది సమాచార ప్రయోజనాల కోసం AI-సృష్టించిన సలహా. ఏదైనా మందులు తీసుకునే ముందు వైద్యుడిని సంప్రదించండి.',
    bookMedicine: 'ఈ మందు బుక్ చేయండి',
    bookTest: 'టెస్ట్ బుక్ చేయండి',
    diabetic: 'డయాబెటిక్?',
    pregnant: 'గర్భవతి?',
    scannerTitle: 'మందుల స్కానర్',
    scannerSubtitle: 'తక్షణ AI విశ్లేషణ కోసం ఏదైనా మందుపై కెమెరా చూపించండి',
    takePhoto: 'ఫోటో తీయండి',
    uploadImage: 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
    analyzing: 'విశ్లేషిస్తోంది…',
    composition: 'కూర్పు',
    sideEffects: 'దుష్ప్రభావాలు',
    warnings: 'హెచ్చరికలు',
    alternatives: 'ప్రత్యామ్నాయాలు',
    prescriptionRequired: 'ప్రిస్క్రిప్షన్ అవసరం',
    overTheCounter: 'ప్రిస్క్రిప్షన్ అవసరం లేదు',
    askAIDoctorTitle: 'ఆరోగ్య AI',
    typingStatus: 'టైప్ చేస్తోంది…',
    alwaysOnline: 'ఎల్లప్పుడూ ఆన్‌లైన్ • Groq AI ద్వారా',
    clearChat: 'క్లియర్',
    today: 'ఈ రోజు',
    thinking: 'ఆలోచిస్తోంది…',
    askPlaceholder: 'మీ లక్షణాలు వివరించండి లేదా వైద్య ప్రశ్న అడగండి...',
    aiDisclaimer: 'Groq AI ద్వారా • ఆరోగ్య AI తప్పులు చేయవచ్చు. వైద్యుడితో ముఖ్యమైన సమాచారాన్ని ధృవీకరించండి.',
    hospitalsTitle: 'సమీప ఆసుపత్రులు',
    findHospitals: 'ఆసుపత్రులు కనుగొనండి',
    distance: 'దూరం',
    openNow: 'ఇప్పుడు తెరిచి ఉంది',
    closed: 'మూసివేయబడింది',
    departments: 'విభాగాలు',
    getDirections: 'దిశలు పొందండి',
    call: 'కాల్ చేయండి',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    appointmentBooked: 'అపాయింట్‌మెంట్ విజయవంతంగా బుక్ అయింది!',
    appointmentBookedMsg: 'మీ అపాయింట్‌మెంట్ బుక్ అయింది. మీకు త్వరలో ధృవీకరణ వస్తుంది.',
    patientName: 'రోగి పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    specialty: 'స్పెషాలిటీ',
    selectDate: 'తేదీ ఎంచుకోండి',
    selectTime: 'సమయం ఎంచుకోండి',
    reasonForVisit: 'సందర్శన కారణం',
    confirmBooking: 'బుకింగ్ నిర్ధారించండి',
    predictorsTitle: 'ఆరోగ్య ప్రమాద అంచనాలు',
    predictorsSubtitle: 'వైద్య డేటా ఆధారంగా AI వ్యాధి ప్రమాద అంచనా',
    riskScore: 'ప్రమాద స్కోర్',
    riskLevel: 'ప్రమాద స్థాయి',
    riskFactors: 'ప్రమాద కారకాలు',
    runPredictor: 'అంచనా చేయండి',
    lowRisk: 'తక్కువ ప్రమాదం',
    moderateRisk: 'మధ్యస్థ ప్రమాదం',
    highRisk: 'ఎక్కువ ప్రమాదం',
    veryHighRisk: 'చాలా ఎక్కువ ప్రమాదం',
    enterHealthData: 'వ్యక్తిగత ప్రమాద అంచనా కోసం ఆరోగ్య డేటా నమోదు చేయండి',
    analyticsTitle: 'ఆరోగ్య విశ్లేషణ',
    analyticsSubtitle: 'మీ ఆరోగ్య ధోరణులను ట్రాక్ చేయండి',
    overview: 'సారాంశం',
    trends: 'ధోరణులు',
    insights: 'అంతర్దృష్టులు',
    crisisTitle: 'సంక్షోభ ప్రతిస్పందన కేంద్రం',
    reportCrisis: 'సంక్షోభం నివేదించండి',
    responder: 'ప్రతిస్పందకుడు',
    status: 'స్థితి',
    location: 'స్థానం',
    mediaTitle: 'ఆరోగ్య మీడియా గ్యాలరీ',
    upload: 'అప్‌లోడ్',
    myUploads: 'నా అప్‌లోడ్‌లు',
    delete: 'తొలగించు',
    preview: 'ప్రివ్యూ',
    poweredByAI: 'AI ద్వారా',
    noResults: 'ఫలితాలు కనుగొనబడలేదు',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    selectAtLeastOne: 'దయచేసి కనీసం ఒకటి ఎంచుకోండి',
    enterAge: 'దయచేసి మీ వయసు నమోదు చేయండి',
    male: 'పురుషుడు',
    female: 'స్త్రీ',
    other: 'ఇతరం',
    select: 'ఎంచుకోండి',
    frequency: 'ఫ్రీక్వెన్సీ',
    duration: 'వ్యవధి',
    timing: 'సమయం',
    purpose: 'ఉద్దేశ్యం',
    navigating: 'నావిగేట్ చేస్తోంది',
    disclaimerText: 'ఏ మందు తీసుకునే ముందు లైసెన్స్ ఉన్న వైద్యుడిని సంప్రదించండి.',
    confirmBooking: 'బుకింగ్ నిర్ధారించండి',
    cancel: 'రద్దు',
    medicalProfile: 'వైద్య ప్రొఫైల్',
    patientName: 'మీ పేరు',
    specialty: 'విశేషజ్ఞత ఎంచుకోండి',
    reasonForVisit: 'సందర్శన కారణం',
    predictorsTitle: 'ఆరోగ్య అంచనాలు',
    predictorsSubtitle: 'నిజమైన వైద్య డేటా ఆధారంగా వ్యక్తిగత ఆరోగ్య ప్రమాద అంచనాలు.',
    analyticsTitle: 'ఆరోగ్య విశ్లేషణ',
    poweredByAI: 'AI ద్వారా',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
  },

  ta: {
    dashboard: 'டாஷ்போர்டு',
    askAIDoctor: 'AI மருத்துவரிடம் கேளுங்கள்',
    symptomChecker: 'அறிகுறி சரிபார்ப்பு',
    medicineFinder: 'மருந்து தேடல்',
    medicineScanner: 'மருந்து ஸ்கேனர்',
    medicalReports: 'மருத்துவ அறிக்கைகள்',
    healthTracker: 'சுகாதார டிராக்கர்',
    appointments: 'நியமனங்கள்',
    emergency: 'அவசரம்',
    hospitals: 'மருத்துவமனைகள்',
    settings: 'அமைப்புகள்',
    searchPlaceholder: 'அறிகுறிகள், மருந்துகள், நோய்கள் பற்றி கேளுங்கள்...',
    onlineDoctor: 'ஆன்லைன் மருத்துவர்',
    nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    viewAll: 'அனைத்தையும் பார்',
    selectLocation: 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    medicineInfo: 'மருந்து தகவல்',
    scanMedicine: 'மருந்தை ஸ்கேன் செய்யுங்கள்',
    scanDescription: 'எந்த மருந்தையும் உடனடியாக ஸ்கேன் செய்து விவரங்களைப் பெறுங்கள்',
    aiDiagnosis: 'AI நோயறிதல் பரிந்துரை',
    healthStats: 'சுகாதார புள்ளிவிவரங்கள்',
    heartRate: 'இதய துடிப்பு',
    bloodPressure: 'இரத்த அழுத்தம்',
    sugarLevel: 'சர்க்கரை அளவு',
    enterSymptoms: 'உங்கள் அறிகுறிகளை கீழே உள்ளிடவும்',
    aiSuggestion: 'AI பரிந்துரை',
    possibleViral: 'வைரஸ் தொற்று இருக்கலாம்',
    condition: 'சாத்தியமான நிலை',
    openFull: 'முழு சரிபார்ப்பைத் திற',
    usedFor: 'பயன்படுத்தப்படுகிறது',
    dosage: 'அளவு',
    availability: 'கிடைக்கும் தன்மை',
    healthPredictors: 'சுகாதார முன்கணிப்பாளர்கள்',
    medicalProfile: 'மருத்துவ சுயவிவரம்',
    myMedicalProfile: 'என் மருத்துவ சுயவிவரம்',
    personalInfo: 'தனிப்பட்ட தகவல்',
    fullName: 'முழு பெயர்',
    age: 'வயது',
    dateOfBirth: 'பிறந்த தேதி',
    gender: 'பாலினம்',
    bloodGroup: 'இரத்த வகை',
    height: 'உயரம் (செமீ)',
    weight: 'எடை (கிகி)',
    medicalConditions: 'மருத்துவ நிலைகள்',
    currentMedications: 'தற்போதைய மருந்துகள்',
    allergies: 'ஒவ்வாமைகள்',
    vitals: 'உயிர் அறிகுறிகள்',
    emergencyContact: 'அவசர தொடர்பு',
    preferredHospitals: 'விரும்பிய மருத்துவமனைகள்',
    saveProfile: 'சுயவிவரத்தை சேமி',
    profileSaved: 'சுயவிவரம் சேமிக்கப்பட்டது!',
    saving: 'சேமிக்கிறது…',
    privateData: 'தனிப்பட்டது — உங்களுக்கு மட்டுமே தெரியும்',
    profileAutoFills: 'சுயவிவரம் சேமிக்கப்பட்டது — SOS எச்சரிக்கைகளில் தானாக நிரப்பும்',
    completeProfile: 'உங்கள் மருத்துவ சுயவிவரத்தை நிரப்புங்கள்',
    organDonor: 'நான் உறுப்பு தானம் செய்பவர்',
    doctorNotes: 'மருத்துவர்களுக்கான சிறப்பு குறிப்புகள்',
    insurance: 'காப்பீடு',
    hasInsurance: 'என்னிடம் சுகாதார காப்பீடு உள்ளது',
    policyNumber: 'பாலிசி எண்',
    profilePicture: 'சுயவிவர படம்',
    uploadPhoto: 'புகைப்படம் பதிவேற்றவும்',
    displayName: 'காட்சி பெயர்',
    email: 'மின்னஞ்சல்',
    bio: 'சுயவிவரம்',
    saveChanges: 'மாற்றங்களை சேமி',
    appearance: 'தோற்றம்',
    lightMode: 'வெளிச்சம்',
    darkMode: 'இருட்டு',
    systemMode: 'கணினி',
    notifications: 'அறிவிப்புகள்',
    privacy: 'தனியுரிமை',
    signOut: 'வெளியேறு',
    deleteAccount: 'கணக்கு மற்றும் தரவை நீக்கு',
    emergency_title: 'அவசரம்?',
    emergency_subtitle: 'உடனடி உதவி ஒரு தட்டு தூரத்தில் உள்ளது. ஹோட்டல் ஊழியர்களுக்கு உடனடியாக எச்சரிக்கை விடுக்க பொத்தானை அழுத்தவும்.',
    reportEmergency: 'அவசரநிலையை புகாரளிக்கவும்',
    yourName: 'உங்கள் பெயர்',
    roomNo: 'அறை எண்',
    floor: 'தளம்',
    emergencyType: 'அவசரநிலை வகை',
    describeEmergency: 'அவசரநிலையை விவரிக்கவும்',
    sendAlert: 'அவசர எச்சரிக்கை அனுப்பு',
    alertCreated: 'எச்சரிக்கை உருவாக்கப்பட்டது',
    helpDispatched: 'உதவி அனுப்பப்படுகிறது',
    medicalProfileLoaded: 'மருத்துவ சுயவிவரம் தானாக ஏற்றப்பட்டது',
    noProfileFound: 'மருத்துவ சுயவிவரம் காணவில்லை.',
    setOneUp: 'ஒன்றை அமைக்கவும்',
    fasterCare: 'விரைவான அவசர சிகிச்சைக்கு.',
    profileSentToHospital: 'இந்த தரவு ஹோட்டல் ஊழியர்கள் மற்றும் மருத்துவமனைக்கு தானாக அனுப்பப்படும்.',
    hospitalPortal: 'மருத்துவமனை அவசர போர்டல்',
    incomingPatients: 'வரும் நோயாளிகள்',
    acknowledgeAlert: 'எச்சரிக்கையை ஏற்கவும்',
    bedReady: 'படுக்கை தயார்',
    patientArrived: 'நோயாளி வந்தார்',
    assignBed: 'படுக்கை ஒதுக்கவும்',
    assignResponder: 'பதிலாளரை நியமிக்கவும்',
    noIncomingAlerts: 'உள்வரும் நோயாளி எச்சரிக்கைகள் இல்லை',
    icdCode: 'ICD-10 குறியீடு',
    condition_label: 'நிலை',
    department: 'துறை',
    bloodType: 'இரத்த வகை',
    knownConditions: 'அறியப்பட்ட நிலைகள்',
    medications: 'மருந்துகள்',
    preferredHospital: 'விரும்பிய மருத்துவமனை',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signIn: 'உள்நுழைவு',
    signUp: 'பதிவு செய்யவும்',
    continueWithGoogle: 'Google உடன் தொடரவும்',
    or: 'அல்லது',
    loading: 'ஏற்றுகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
    back: 'திரும்பு',
    next: 'அடுத்து',
    submit: 'சமர்ப்பி',
    refresh: 'புதுப்பி',
    connected: 'இணைக்கப்பட்டது',
    connecting: 'இணைக்கிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    symptomCheckerTitle: 'அறிகுறி சோதனை',
    symptomCheckerSubtitle: 'AI மூலம் மருந்து பரிந்துரைகள்',
    patientProfile: 'நோயாளி சுயவிவரம்',
    selectSymptoms: 'அறிகுறிகளைத் தேர்ந்தெடுக்கவும்',
    searchSymptoms: 'அறிகுறிகளைத் தேடுங்கள்…',
    addOtherSymptom: 'வேறு அறிகுறி சேர்க்கவும்…',
    add: 'சேர்',
    analyzeSymptoms: 'அறிகுறிகளை பகுப்பாய்வு செய்',
    analyzingAI: 'AI பகுப்பாய்வு செய்கிறது…',
    aiMedicineRecommendations: 'AI மருந்து பரிந்துரைகள்',
    fillProfilePrompt: 'உங்கள் சுயவிவரத்தை நிரப்பி அறிகுறிகளைத் தேர்ந்தெடுக்கவும்.',
    analyzingYourSymptoms: 'உங்கள் அறிகுறிகளை பகுப்பாய்வு செய்கிறது…',
    aiReviewingProfile: 'AI உங்கள் சுயவிவரத்தை மதிப்பாய்வு செய்கிறது',
    aiDiagnosisTitle: 'AI நோயறிதல்',
    basedOnSymptoms: 'உங்கள் அறிகுறிகள் அடிப்படையில்',
    recommendedMedicines: 'பரிந்துரைக்கப்பட்ட மருந்துகள்',
    generalAdvice: 'பொது ஆலோசனை',
    whenToSeeDoctor: 'மருத்துவரை எப்போது சந்திக்க வேண்டும்',
    disclaimerText: 'இது AI உருவாக்கிய ஆலோசனை. மருத்துவரை அணுகவும்.',
    disclaimerBanner: 'இது தகவல் நோக்கங்களுக்கான AI ஆலோசனை. மருந்து எடுக்கும் முன் மருத்துவரை அணுகவும்.',
    bookMedicine: 'இந்த மருந்தை புக் செய்',
    bookTest: 'சோதனை புக் செய்',
    diabetic: 'நீரிழிவு?',
    pregnant: 'கர்ப்பமா?',
    scannerTitle: 'மருந்து ஸ்கேனர்',
    scannerSubtitle: 'உடனடி AI பகுப்பாய்விற்கு எந்த மருந்தையும் ஸ்கேன் செய்யுங்கள்',
    takePhoto: 'புகைப்படம் எடு',
    uploadImage: 'படத்தை பதிவேற்றம் செய்',
    analyzing: 'பகுப்பாய்வு செய்கிறது…',
    composition: 'கலவை',
    sideEffects: 'பக்க விளைவுகள்',
    warnings: 'எச்சரிக்கைகள்',
    alternatives: 'மாற்று மருந்துகள்',
    prescriptionRequired: 'மருந்துச் சீட்டு தேவை',
    overTheCounter: 'மருந்துச் சீட்டு தேவையில்லை',
    askAIDoctorTitle: 'ஆரோக்ய AI',
    typingStatus: 'தட்டச்சு செய்கிறது…',
    alwaysOnline: 'எப்போதும் ஆன்லைன் • Groq AI',
    clearChat: 'அழி',
    today: 'இன்று',
    thinking: 'யோசிக்கிறது…',
    askPlaceholder: 'உங்கள் அறிகுறிகளை விவரிக்கவும்...',
    aiDisclaimer: 'Groq AI • ஆரோக்ய AI தவறு செய்யலாம். மருத்துவரிடம் சரிபார்க்கவும்.',
    hospitalsTitle: 'அருகிலுள்ள மருத்துவமனைகள்',
    findHospitals: 'மருத்துவமனைகளைக் கண்டறி',
    distance: 'தூரம்',
    openNow: 'இப்போது திறந்திருக்கிறது',
    closed: 'மூடப்பட்டது',
    departments: 'துறைகள்',
    getDirections: 'திசைகளைப் பெறு',
    call: 'அழை',
    bookAppointment: 'சந்திப்பை பதிவு செய்',
    appointmentBooked: 'சந்திப்பு வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    appointmentBookedMsg: 'உங்கள் சந்திப்பு பதிவு செய்யப்பட்டது.',
    patientName: 'நோயாளி பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    specialty: 'சிறப்பு',
    selectDate: 'தேதி தேர்ந்தெடு',
    selectTime: 'நேரம் தேர்ந்தெடு',
    reasonForVisit: 'வருகையின் காரணம்',
    confirmBooking: 'பதிவை உறுதிசெய்',
    predictorsTitle: 'ஆரோக்கிய ஆபத்து முன்கணிப்பு',
    predictorsSubtitle: 'AI நோய் ஆபத்து மதிப்பீடு',
    riskScore: 'ஆபத்து மதிப்பெண்',
    riskLevel: 'ஆபத்து நிலை',
    riskFactors: 'ஆபத்து காரணிகள்',
    runPredictor: 'முன்கணிப்பு இயக்கு',
    lowRisk: 'குறைந்த ஆபத்து',
    moderateRisk: 'மிதமான ஆபத்து',
    highRisk: 'அதிக ஆபத்து',
    veryHighRisk: 'மிக அதிக ஆபத்து',
    enterHealthData: 'ஆரோக்கிய தரவை உள்ளிடுங்கள்',
    analyticsTitle: 'ஆரோக்கிய பகுப்பாய்வு',
    analyticsSubtitle: 'உங்கள் ஆரோக்கிய போக்குகளைக் கண்காணிக்கவும்',
    overview: 'கண்ணோட்டம்',
    trends: 'போக்குகள்',
    insights: 'நுண்ணறிவுகள்',
    crisisTitle: 'நெருக்கடி மையம்',
    reportCrisis: 'நெருக்கடி புகார்',
    responder: 'பதிலளிப்பவர்',
    status: 'நிலை',
    location: 'இடம்',
    mediaTitle: 'ஆரோக்கிய மீடியா',
    upload: 'பதிவேற்றம்',
    myUploads: 'எனது பதிவேற்றங்கள்',
    delete: 'நீக்கு',
    preview: 'முன்னோட்டம்',
    poweredByAI: 'AI மூலம்',
    noResults: 'முடிவுகள் இல்லை',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    selectAtLeastOne: 'குறைந்தது ஒன்றைத் தேர்ந்தெடுக்கவும்',
    enterAge: 'உங்கள் வயதை உள்ளிடவும்',
    male: 'ஆண்',
    female: 'பெண்',
    other: 'மற்றவை',
    select: 'தேர்ந்தெடு',
    frequency: 'அலைவரிசை',
    duration: 'காலம்',
    timing: 'நேரம்',
    purpose: 'நோக்கம்',
    quizTitle: 'AI ஆரோக்கிய வினாடி வினா',
    quizSubtitle: 'எந்த ஆரோக்கிய தலைப்பிலும் AI வினா',
    generateQuiz: 'வினா உருவாக்கு',
    generating: 'உருவாக்குகிறது...',
    startQuiz: 'வினா தொடங்கு',
    nextQuestion: 'அடுத்த கேள்வி',
    viewResults: 'முடிவுகளைப் பார்',
    retryQuiz: 'மீண்டும் முயற்சி',
    allCategories: 'அனைத்து பிரிவுகள்',
    correct: 'சரி',
    wrong: 'தவறு',
    accuracy: 'துல்லியம்',
    explanation: 'விளக்கம்',
    questionBreakdown: 'கேள்வி பகுப்பாய்வு',
    orPickCategory: 'அல்லது ஒரு பிரிவை தேர்ந்தெடுக்கவும்',
    generateWithAI: 'AI உடன் வினா உருவாக்கு',
    aiGeneratingQuiz: 'AI உங்கள் வினா கேள்விகளை உருவாக்குகிறது...',
    medicineName: 'மருந்து பெயர்',
    searchMedicine: 'மருந்து தேடு',
    price: 'விலை',
    manufacturer: 'உற்பத்தியாளர்',
    type: 'வகை',
    uses: 'பயன்கள்',
    diagnosticCentre: 'நோயறிதல் மையம்',
    bookNow: 'இப்போது புக் செய்',
    doctors: 'மருத்துவர்கள்',
    findDoctors: 'மருத்துவர்களைக் கண்டறி',
    videoCall: 'வீடியோ அழைப்பு',
    reports: 'அறிக்கைகள்',
    healthcareNavigator: 'சுகாதார வழிகாட்டி',
    navigating: 'செல்கிறது',
    disclaimerText: 'மருந்து எடுக்கும் முன் உரிமம் பெற்ற மருத்துவரை அணுகவும்.',
    confirmBooking: 'முன்பதிவை உறுதிப்படுத்து',
    cancel: 'ரத்து',
    medicalProfile: 'மருத்துவ சுயவிவரம்',
    patientName: 'உங்கள் பெயர்',
    specialty: 'நிபுணத்துவம் தேர்ந்தெடுக்கவும்',
    reasonForVisit: 'சந்திப்பு காரணம்',
    predictorsTitle: 'ஆரோக்கிய கணிப்புகள்',
    predictorsSubtitle: 'உண்மையான மருத்துவ தரவு அடிப்படையில் தனிப்பயன் ஆரோக்கிய ஆபத்து மதிப்பீடு.',
    analyticsTitle: 'ஆரோக்கிய பகுப்பாய்வு',
    poweredByAI: 'AI இயக்கம்',
    bookAppointment: 'சந்திப்பு முன்பதிவு',
  },

  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', askAIDoctor: 'AI ವೈದ್ಯರನ್ನು ಕೇಳಿ', symptomChecker: 'ಲಕ್ಷಣಗಳ ತಪಾಸಣೆ',
    medicineFinder: 'ಔಷಧ ಶೋಧಕ', medicineScanner: 'ಔಷಧ ಸ್ಕ್ಯಾನರ್', medicalReports: 'ವೈದ್ಯಕೀಯ ವರದಿಗಳು',
    healthTracker: 'ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್', appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು', emergency: 'ತುರ್ತು',
    hospitals: 'ಆಸ್ಪತ್ರೆಗಳು', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    searchPlaceholder: 'ಲಕ್ಷಣಗಳು, ಔಷಧಗಳು, ಕಾಯಿಲೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...', onlineDoctor: 'ಆನ್‌ಲೈನ್ ವೈದ್ಯರು',
    nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ', selectLocation: 'ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    medicineInfo: 'ಔಷಧ ಮಾಹಿತಿ', scanMedicine: 'ಔಷಧ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanDescription: 'ತಕ್ಷಣದ ವಿವರಗಳನ್ನು ಪಡೆಯಲು ಯಾವುದೇ ಔಷಧವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    aiDiagnosis: 'AI ರೋಗನಿರ್ಣಯ ಸಲಹೆ', healthStats: 'ಆರೋಗ್ಯ ಅಂಕಿಅಂಶಗಳು', heartRate: 'ಹೃದಯ ಬಡಿತ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ', sugarLevel: 'ಸಕ್ಕರೆ ಮಟ್ಟ', enterSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಕೆಳಗೆ ನಮೂದಿಸಿ',
    aiSuggestion: 'AI ಸಲಹೆ', possibleViral: 'ವೈರಲ್ ಸೋಂಕು ಇರಬಹುದು', condition: 'ಸಂಭವನೀಯ ಸ್ಥಿತಿ',
    openFull: 'ಪೂರ್ಣ ತಪಾಸಣೆ ತೆರೆಯಿರಿ', usedFor: 'ಬಳಸಲಾಗುತ್ತದೆ', dosage: 'ಡೋಸೇಜ್', availability: 'ಲಭ್ಯತೆ',
    healthPredictors: 'ಆರೋಗ್ಯ ಮುನ್ಸೂಚಕಗಳು',
    medicalProfile: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್', myMedicalProfile: 'ನನ್ನ ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್',
    personalInfo: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', age: 'ವಯಸ್ಸು', dateOfBirth: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    gender: 'ಲಿಂಗ', bloodGroup: 'ರಕ್ತ ಗುಂಪು', height: 'ಎತ್ತರ (ಸೆಮಿ)', weight: 'ತೂಕ (ಕಿಗ್ರಾ)',
    medicalConditions: 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಗಳು', currentMedications: 'ಪ್ರಸ್ತುತ ಔಷಧಗಳು', allergies: 'ಅಲರ್ಜಿಗಳು',
    vitals: 'ಜೀವ ಸಂಕೇತಗಳು', emergencyContact: 'ತುರ್ತು ಸಂಪರ್ಕ', preferredHospitals: 'ಆದ್ಯತೆಯ ಆಸ್ಪತ್ರೆಗಳು',
    saveProfile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ', profileSaved: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ!', saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    privateData: 'ಖಾಸಗಿ — ನಿಮಗೆ ಮಾತ್ರ ಗೋಚರಿಸುತ್ತದೆ',
    profileAutoFills: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ — SOS ಎಚ್ಚರಿಕೆಗಳಲ್ಲಿ ಸ್ವಯಂ ತುಂಬಿಸುತ್ತದೆ',
    completeProfile: 'ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    organDonor: 'ನಾನು ಅಂಗ ದಾನಿ', doctorNotes: 'ವೈದ್ಯರಿಗೆ ವಿಶೇಷ ಟಿಪ್ಪಣಿಗಳು',
    insurance: 'ವಿಮೆ', hasInsurance: 'ನನಗೆ ಆರೋಗ್ಯ ವಿಮೆ ಇದೆ', policyNumber: 'ಪಾಲಿಸಿ ಸಂಖ್ಯೆ',
    profilePicture: 'ಪ್ರೊಫೈಲ್ ಚಿತ್ರ', uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು', email: 'ಇಮೇಲ್', bio: 'ಪರಿಚಯ', saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    appearance: 'ನೋಟ', lightMode: 'ಬೆಳಕು', darkMode: 'ಕತ್ತಲೆ', systemMode: 'ಸಿಸ್ಟಮ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು', privacy: 'ಗೌಪ್ಯತೆ', signOut: 'ಸೈನ್ ಔಟ್',
    deleteAccount: 'ಖಾತೆ ಮತ್ತು ಡೇಟಾ ಅಳಿಸಿ',
    emergency_title: 'ತುರ್ತು?', emergency_subtitle: 'ತಕ್ಷಣ ಸಹಾಯ ಒಂದು ಟ್ಯಾಪ್ ದೂರದಲ್ಲಿದೆ.',
    reportEmergency: 'ತುರ್ತನ್ನು ವರದಿ ಮಾಡಿ', yourName: 'ನಿಮ್ಮ ಹೆಸರು', roomNo: 'ಕೋಣೆ ಸಂಖ್ಯೆ', floor: 'ಮಹಡಿ',
    emergencyType: 'ತುರ್ತು ವಿಧ', describeEmergency: 'ತುರ್ತನ್ನು ವಿವರಿಸಿ', sendAlert: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',
    alertCreated: 'ಎಚ್ಚರಿಕೆ ರಚಿಸಲಾಗಿದೆ', helpDispatched: 'ಸಹಾಯ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ',
    medicalProfileLoaded: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಸ್ವಯಂ ಲೋಡ್ ಆಗಿದೆ',
    noProfileFound: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಕಂಡುಬಂದಿಲ್ಲ.', setOneUp: 'ಒಂದು ಸೆಟಪ್ ಮಾಡಿ',
    fasterCare: 'ವೇಗವಾದ ತುರ್ತು ಆರೈಕೆಗಾಗಿ.',
    profileSentToHospital: 'ಈ ಡೇಟಾ ಹೋಟೆಲ್ ಸಿಬ್ಬಂದಿ ಮತ್ತು ಆಸ್ಪತ್ರೆಗೆ ಸ್ವಯಂ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
    hospitalPortal: 'ಆಸ್ಪತ್ರೆ ತುರ್ತು ಪೋರ್ಟಲ್', incomingPatients: 'ಒಳಬರುವ ರೋಗಿಗಳು',
    acknowledgeAlert: 'ಎಚ್ಚರಿಕೆ ಸ್ವೀಕರಿಸಿ', bedReady: 'ಹಾಸಿಗೆ ಸಿದ್ಧ', patientArrived: 'ರೋಗಿ ಬಂದರು',
    assignBed: 'ಹಾಸಿಗೆ ನಿಯೋಜಿಸಿ', assignResponder: 'ಪ್ರತಿಸ್ಪಂದಕ ನಿಯೋಜಿಸಿ',
    noIncomingAlerts: 'ಒಳಬರುವ ರೋಗಿ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ', icdCode: 'ICD-10 ಕೋಡ್', condition_label: 'ಸ್ಥಿತಿ',
    department: 'ವಿಭಾಗ', bloodType: 'ರಕ್ತ ವಿಧ', knownConditions: 'ತಿಳಿದ ಸ್ಥಿತಿಗಳು',
    medications: 'ಔಷಧಗಳು', preferredHospital: 'ಆದ್ಯತೆಯ ಆಸ್ಪತ್ರೆ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ', signIn: 'ಸೈನ್ ಇನ್', signUp: 'ಸೈನ್ ಅಪ್',
    continueWithGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ', or: 'ಅಥವಾ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', submit: 'ಸಲ್ಲಿಸಿ', refresh: 'ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    connected: 'ಸಂಪರ್ಕಿತ', connecting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...', error: 'ದೋಷ', success: 'ಯಶಸ್ಸು',
    symptomCheckerTitle: 'ಲಕ್ಷಣ ಪರೀಕ್ಷಕ',
    symptomCheckerSubtitle: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರಿತ AI ಔಷಧ ಶಿಫಾರಸುಗಳು',
    patientProfile: 'ರೋಗಿ ಪ್ರೊಫೈಲ್',
    selectSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    searchSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಹುಡುಕಿ…',
    addOtherSymptom: 'ಇತರ ಲಕ್ಷಣ ಸೇರಿಸಿ…',
    add: 'ಸೇರಿಸಿ',
    analyzeSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    analyzingAI: 'AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    aiMedicineRecommendations: 'AI ಔಷಧ ಶಿಫಾರಸುಗಳು',
    fillProfilePrompt: 'ನಿಮ್ಮ ರೋಗಿ ಪ್ರೊಫೈಲ್ ತುಂಬಿ ಮತ್ತು ಲಕ್ಷಣಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    analyzingYourSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    aiReviewingProfile: 'ನಮ್ಮ AI ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದೆ',
    aiDiagnosisTitle: 'AI ರೋಗನಿರ್ಣಯ',
    basedOnSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳು ಮತ್ತು ಪ್ರೊಫೈಲ್ ಆಧಾರಿತ',
    recommendedMedicines: 'ಶಿಫಾರಸು ಮಾಡಿದ ಔಷಧಗಳು',
    generalAdvice: 'ಸಾಮಾನ್ಯ ಸಲಹೆ',
    whenToSeeDoctor: 'ವೈದ್ಯರನ್ನು ಯಾವಾಗ ಭೇಟಿ ಮಾಡಬೇಕು',
    disclaimerText: 'ಇದು AI-ರಚಿತ ಸಲಹೆ. ಅರ್ಹ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    disclaimerBanner: 'ಇದು ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ AI ಸಲಹೆ. ಯಾವುದೇ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊದಲು ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    bookMedicine: 'ಈ ಔಷಧ ಬುಕ್ ಮಾಡಿ',
    bookTest: 'ಟೆಸ್ಟ್ ಬುಕ್ ಮಾಡಿ',
    diabetic: 'ಮಧುಮೇಹ?',
    pregnant: 'ಗರ್ಭಿಣಿ?',
    scannerTitle: 'ಔಷಧ ಸ್ಕ್ಯಾನರ್',
    scannerSubtitle: 'ತಕ್ಷಣದ AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಯಾವುದೇ ಔಷಧವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    uploadImage: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    composition: 'ಸಂಯೋಜನೆ',
    sideEffects: 'ಅಡ್ಡ ಪರಿಣಾಮಗಳು',
    warnings: 'ಎಚ್ಚರಿಕೆಗಳು',
    alternatives: 'ಪರ್ಯಾಯಗಳು',
    prescriptionRequired: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಗತ್ಯ',
    overTheCounter: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಗತ್ಯವಿಲ್ಲ',
    askAIDoctorTitle: 'ಆರೋಗ್ಯ AI',
    typingStatus: 'ಟೈಪ್ ಮಾಡುತ್ತಿದೆ…',
    alwaysOnline: 'ಯಾವಾಗಲೂ ಆನ್‌ಲೈನ್ • Groq AI',
    clearChat: 'ಅಳಿಸಿ',
    today: 'ಇಂದು',
    thinking: 'ಯೋಚಿಸುತ್ತಿದೆ…',
    askPlaceholder: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ ಅಥವಾ ವೈದ್ಯಕೀಯ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    aiDisclaimer: 'Groq AI • ಆರೋಗ್ಯ AI ತಪ್ಪುಗಳನ್ನು ಮಾಡಬಹುದು. ವೈದ್ಯರೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.',
    hospitalsTitle: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    findHospitals: 'ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ',
    distance: 'ದೂರ',
    openNow: 'ಈಗ ತೆರೆದಿದೆ',
    closed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    departments: 'ವಿಭಾಗಗಳು',
    getDirections: 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    appointmentBooked: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಯಶಸ್ವಿಯಾಗಿ ಬುಕ್ ಆಗಿದೆ!',
    appointmentBookedMsg: 'ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಆಗಿದೆ. ಶೀಘ್ರದಲ್ಲೇ ದೃಢೀಕರಣ ಬರುತ್ತದೆ.',
    patientName: 'ರೋಗಿ ಹೆಸರು',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    specialty: 'ವಿಶೇಷತೆ',
    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    selectTime: 'ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
    reasonForVisit: 'ಭೇಟಿಯ ಕಾರಣ',
    confirmBooking: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
    predictorsTitle: 'ಆರೋಗ್ಯ ಅಪಾಯ ಮುನ್ಸೂಚಕಗಳು',
    predictorsSubtitle: 'ವೈದ್ಯಕೀಯ ಡೇಟಾ ಆಧಾರಿತ AI ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ',
    riskScore: 'ಅಪಾಯ ಸ್ಕೋರ್',
    riskLevel: 'ಅಪಾಯ ಮಟ್ಟ',
    riskFactors: 'ಅಪಾಯ ಕಾರಣಗಳು',
    runPredictor: 'ಮುನ್ಸೂಚಕ ಓಡಿಸಿ',
    lowRisk: 'ಕಡಿಮೆ ಅಪಾಯ',
    moderateRisk: 'ಮಧ್ಯಮ ಅಪಾಯ',
    highRisk: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    veryHighRisk: 'ಅತಿ ಹೆಚ್ಚಿನ ಅಪಾಯ',
    enterHealthData: 'ವೈಯಕ್ತಿಕ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ ಆರೋಗ್ಯ ಡೇಟಾ ನಮೂದಿಸಿ',
    analyticsTitle: 'ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ',
    analyticsSubtitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    overview: 'ಅವಲೋಕನ',
    trends: 'ಪ್ರವೃತ್ತಿಗಳು',
    insights: 'ಒಳನೋಟಗಳು',
    crisisTitle: 'ಸಂಕಷ್ಟ ಪ್ರತಿಕ್ರಿಯೆ ಕೇಂದ್ರ',
    reportCrisis: 'ಸಂಕಷ್ಟ ವರದಿ ಮಾಡಿ',
    responder: 'ಪ್ರತಿಸ್ಪಂದಕ',
    status: 'ಸ್ಥಿತಿ',
    location: 'ಸ್ಥಳ',
    mediaTitle: 'ಆರೋಗ್ಯ ಮಾಧ್ಯಮ ಗ್ಯಾಲರಿ',
    upload: 'ಅಪ್‌ಲೋಡ್',
    myUploads: 'ನನ್ನ ಅಪ್‌ಲೋಡ್‌ಗಳು',
    delete: 'ಅಳಿಸಿ',
    preview: 'ಮುನ್ನೋಟ',
    poweredByAI: 'AI ಮೂಲಕ',
    noResults: 'ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    selectAtLeastOne: 'ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    enterAge: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಯಸ್ಸು ನಮೂದಿಸಿ',
    male: 'ಪುರುಷ',
    female: 'ಮಹಿಳೆ',
    other: 'ಇತರೆ',
    select: 'ಆಯ್ಕೆಮಾಡಿ',
    frequency: 'ಆವರ್ತನ',
    duration: 'ಅವಧಿ',
    timing: 'ಸಮಯ',
    purpose: 'ಉದ್ದೇಶ',
    quizTitle: 'AI ಆರೋಗ್ಯ ಕ್ವಿಜ್',
    quizSubtitle: 'ಯಾವುದೇ ಆರೋಗ್ಯ ವಿಷಯದ ಮೇಲೆ AI ಕ್ವಿಜ್',
    generateQuiz: 'ಕ್ವಿಜ್ ಉತ್ಪಾದಿಸಿ',
    generating: 'ಉತ್ಪಾದಿಸಲಾಗುತ್ತಿದೆ...',
    startQuiz: 'ಕ್ವಿಜ್ ಪ್ರಾರಂಭಿಸಿ',
    nextQuestion: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ',
    viewResults: 'ಫಲಿತಾಂಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    retryQuiz: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    allCategories: 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    correct: 'ಸರಿ',
    wrong: 'ತಪ್ಪು',
    accuracy: 'ನಿಖರತೆ',
    explanation: 'ವಿವರಣೆ',
    questionBreakdown: 'ಪ್ರಶ್ನೆ ವಿಶ್ಲೇಷಣೆ',
    orPickCategory: 'ಅಥವಾ ಒಂದು ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    generateWithAI: 'AI ಜೊತೆ ಕ್ವಿಜ್ ಉತ್ಪಾದಿಸಿ',
    aiGeneratingQuiz: 'AI ನಿಮ್ಮ ಕ್ವಿಜ್ ಪ್ರಶ್ನೆಗಳನ್ನು ರಚಿಸುತ್ತಿದೆ...',
    medicineName: 'ಔಷಧ ಹೆಸರು',
    searchMedicine: 'ಔಷಧ ಹುಡುಕಿ',
    price: 'ಬೆಲೆ',
    manufacturer: 'ತಯಾರಕ',
    type: 'ವಿಧ',
    uses: 'ಉಪಯೋಗಗಳು',
    diagnosticCentre: 'ರೋಗನಿರ್ಣಯ ಕೇಂದ್ರ',
    bookNow: 'ಈಗ ಬುಕ್ ಮಾಡಿ',
    doctors: 'ವೈದ್ಯರು',
    findDoctors: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    videoCall: 'ವೀಡಿಯೋ ಕರೆ',
    reports: 'ವರದಿಗಳು',
    healthcareNavigator: 'ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶಿ',
    navigating: 'ನ್ಯಾವಿಗೇಟ್ ಆಗುತ್ತಿದೆ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    medicalProfile: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್',
  },

  mr: {
    dashboard: 'डॅशबोर्ड', askAIDoctor: 'AI डॉक्टरांना विचारा', symptomChecker: 'लक्षण तपासक',
    medicineFinder: 'औषध शोधक', medicineScanner: 'औषध स्कॅनर', medicalReports: 'वैद्यकीय अहवाल',
    healthTracker: 'आरोग्य ट्रॅकर', appointments: 'अपॉइंटमेंट्स', emergency: 'आणीबाणी',
    hospitals: 'रुग्णालये', settings: 'सेटिंग्ज',
    searchPlaceholder: 'लक्षणे, औषधे, आजारांबद्दल विचारा...', onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'नजीकची रुग्णालये', viewAll: 'सर्व पहा', selectLocation: 'स्थान निवडा',
    medicineInfo: 'औषध माहिती', scanMedicine: 'औषध स्कॅन करा',
    scanDescription: 'कोणतेही औषध त्वरित स्कॅन करा आणि तपशील मिळवा',
    aiDiagnosis: 'AI निदान सूचना', healthStats: 'आरोग्य आकडेवारी', heartRate: 'हृदय गती',
    bloodPressure: 'रक्तदाब', sugarLevel: 'शुगर लेव्हल', enterSymptoms: 'खाली आपली लक्षणे प्रविष्ट करा',
    aiSuggestion: 'AI सूचना', possibleViral: 'संभाव्य व्हायरल इन्फेक्शन', condition: 'संभाव्य स्थिती',
    openFull: 'पूर्ण तपासक उघडा', usedFor: 'साठी वापरले जाते', dosage: 'डोस', availability: 'उपलब्धता',
    healthPredictors: 'आरोग्य भविष्यवेत्ता',
    medicalProfile: 'वैद्यकीय प्रोफाइल', myMedicalProfile: 'माझी वैद्यकीय प्रोफाइल',
    personalInfo: 'वैयक्तिक माहिती', fullName: 'पूर्ण नाव', age: 'वय', dateOfBirth: 'जन्म तारीख',
    gender: 'लिंग', bloodGroup: 'रक्त गट', height: 'उंची (सेमी)', weight: 'वजन (किग्रा)',
    medicalConditions: 'वैद्यकीय परिस्थिती', currentMedications: 'सध्याची औषधे', allergies: 'ऍलर्जी',
    vitals: 'जीव संकेत', emergencyContact: 'आणीबाणी संपर्क', preferredHospitals: 'पसंतीची रुग्णालये',
    saveProfile: 'प्रोफाइल जतन करा', profileSaved: 'प्रोफाइल जतन केली!', saving: 'जतन होत आहे…',
    privateData: 'खाजगी — फक्त तुम्हाला दिसते',
    profileAutoFills: 'प्रोफाइल जतन — SOS अलर्टमध्ये आपोआप भरते',
    completeProfile: 'तुमची वैद्यकीय प्रोफाइल पूर्ण करा',
    organDonor: 'मी अवयव दाता आहे', doctorNotes: 'डॉक्टरांसाठी विशेष नोट्स',
    insurance: 'विमा', hasInsurance: 'माझ्याकडे आरोग्य विमा आहे', policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफाइल चित्र', uploadPhoto: 'फोटो अपलोड करा',
    displayName: 'प्रदर्शन नाव', email: 'ईमेल', bio: 'परिचय', saveChanges: 'बदल जतन करा',
    appearance: 'दिसणे', lightMode: 'प्रकाश', darkMode: 'अंधार', systemMode: 'सिस्टम',
    notifications: 'सूचना', privacy: 'गोपनीयता', signOut: 'साइन आउट',
    deleteAccount: 'खाते आणि डेटा हटवा',
    emergency_title: 'आणीबाणी?', emergency_subtitle: 'त्वरित मदत एका टॅपवर आहे.',
    reportEmergency: 'आणीबाणी नोंदवा', yourName: 'तुमचे नाव', roomNo: 'खोली क्रमांक', floor: 'मजला',
    emergencyType: 'आणीबाणीचा प्रकार', describeEmergency: 'आणीबाणीचे वर्णन करा',
    sendAlert: 'आणीबाणी अलर्ट पाठवा', alertCreated: 'अलर्ट तयार झाला', helpDispatched: 'मदत पाठवली जात आहे',
    medicalProfileLoaded: 'वैद्यकीय प्रोफाइल आपोआप लोड झाली',
    noProfileFound: 'वैद्यकीय प्रोफाइल आढळली नाही.', setOneUp: 'एक सेट करा',
    fasterCare: 'जलद आणीबाणी काळजीसाठी.',
    profileSentToHospital: 'हा डेटा हॉटेल कर्मचारी आणि रुग्णालयाला आपोआप पाठवला जाईल.',
    hospitalPortal: 'रुग्णालय आणीबाणी पोर्टल', incomingPatients: 'येणारे रुग्ण',
    acknowledgeAlert: 'अलर्ट स्वीकारा', bedReady: 'बेड तयार', patientArrived: 'रुग्ण आला',
    assignBed: 'बेड नियुक्त करा', assignResponder: 'प्रतिसादकर्ता नियुक्त करा',
    noIncomingAlerts: 'येणारे रुग्ण अलर्ट नाहीत', icdCode: 'ICD-10 कोड', condition_label: 'स्थिती',
    department: 'विभाग', bloodType: 'रक्त प्रकार', knownConditions: 'ज्ञात परिस्थिती',
    medications: 'औषधे', preferredHospital: 'पसंतीचे रुग्णालय',
    welcomeBack: 'पुन्हा स्वागत', signIn: 'साइन इन', signUp: 'साइन अप',
    continueWithGoogle: 'Google सह सुरू ठेवा', or: 'किंवा',
    loading: 'लोड होत आहे...', save: 'जतन करा', cancel: 'रद्द करा', close: 'बंद करा',
    back: 'मागे', next: 'पुढे', submit: 'सबमिट करा', refresh: 'रिफ्रेश करा',
    connected: 'कनेक्ट झाले', connecting: 'कनेक्ट होत आहे...', error: 'त्रुटी', success: 'यश',
  },

  bn: {
    dashboard: 'ড্যাশবোর্ড', askAIDoctor: 'AI ডাক্তারকে জিজ্ঞাসা করুন', symptomChecker: 'উপসর্গ পরীক্ষক',
    medicineFinder: 'ওষুধ খোঁজার যন্ত্র', medicineScanner: 'ওষুধ স্ক্যানার', medicalReports: 'মেডিক্যাল রিপোর্ট',
    healthTracker: 'স্বাস্থ্য ট্র্যাকার', appointments: 'অ্যাপয়েন্টমেন্ট', emergency: 'জরুরী',
    hospitals: 'হাসপাতাল', settings: 'সেটিংস',
    searchPlaceholder: 'উপসর্গ, ওষুধ, রোগ সম্পর্কে জিজ্ঞাসা করুন...', onlineDoctor: 'অনলাইন ডাক্তার',
    nearbyHospitals: 'নিকটস্থ হাসপাতাল', viewAll: 'সব দেখুন', selectLocation: 'স্থান নির্বাচন করুন',
    medicineInfo: 'ওষুধের তথ্য', scanMedicine: 'ওষুধ স্ক্যান করুন',
    scanDescription: 'যেকোনো ওষুধ স্ক্যান করুন এবং বিস্তারিত জানুন',
    aiDiagnosis: 'AI ডায়াগনোসিস পরামর্শ', healthStats: 'স্বাস্থ্য পরিসংখ্যান', heartRate: 'হৃৎস্পন্দন',
    bloodPressure: 'রক্তচাপ', sugarLevel: 'সুগার লেভেল', enterSymptoms: 'নিচে আপনার উপসর্গ লিখুন',
    aiSuggestion: 'AI পরামর্শ', possibleViral: 'সম্ভাব্য ভাইরাল সংক্রমণ', condition: 'সম্ভাব্য অবস্থা',
    openFull: 'পুরো পরীক্ষক খুলুন', usedFor: 'জন্য ব্যবহৃত', dosage: 'ডোজ', availability: 'উপলব্ধতা',
    healthPredictors: 'স্বাস্থ্য ভবিষ্যৎবক্তা',
    medicalProfile: 'মেডিকেল প্রোফাইল', myMedicalProfile: 'আমার মেডিকেল প্রোফাইল',
    personalInfo: 'ব্যক্তিগত তথ্য', fullName: 'পুরো নাম', age: 'বয়স', dateOfBirth: 'জন্ম তারিখ',
    gender: 'লিঙ্গ', bloodGroup: 'রক্তের গ্রুপ', height: 'উচ্চতা (সেমি)', weight: 'ওজন (কেজি)',
    medicalConditions: 'চিকিৎসা অবস্থা', currentMedications: 'বর্তমান ওষুধ', allergies: 'অ্যালার্জি',
    vitals: 'গুরুত্বপূর্ণ লক্ষণ', emergencyContact: 'জরুরী যোগাযোগ', preferredHospitals: 'পছন্দের হাসপাতাল',
    saveProfile: 'প্রোফাইল সংরক্ষণ করুন', profileSaved: 'প্রোফাইল সংরক্ষিত!', saving: 'সংরক্ষণ হচ্ছে…',
    privateData: 'ব্যক্তিগত — শুধুমাত্র আপনাকে দেখায়',
    profileAutoFills: 'প্রোফাইল সংরক্ষিত — SOS সতর্কতায় স্বয়ংক্রিয়ভাবে পূরণ হয়',
    completeProfile: 'আপনার মেডিকেল প্রোফাইল সম্পন্ন করুন',
    organDonor: 'আমি একজন অঙ্গ দাতা', doctorNotes: 'ডাক্তারদের জন্য বিশেষ নোট',
    insurance: 'বীমা', hasInsurance: 'আমার স্বাস্থ্য বীমা আছে', policyNumber: 'পলিসি নম্বর',
    profilePicture: 'প্রোফাইল ছবি', uploadPhoto: 'ছবি আপলোড করুন',
    displayName: 'প্রদর্শনী নাম', email: 'ইমেইল', bio: 'জীবনী', saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    appearance: 'চেহারা', lightMode: 'আলো', darkMode: 'অন্ধকার', systemMode: 'সিস্টেম',
    notifications: 'বিজ্ঞপ্তি', privacy: 'গোপনীয়তা', signOut: 'সাইন আউট',
    deleteAccount: 'অ্যাকাউন্ট এবং ডেটা মুছুন',
    emergency_title: 'জরুরী?', emergency_subtitle: 'তাৎক্ষণিক সাহায্য এক ট্যাপ দূরে।',
    reportEmergency: 'জরুরী রিপোর্ট করুন', yourName: 'আপনার নাম', roomNo: 'ঘর নম্বর', floor: 'তলা',
    emergencyType: 'জরুরী ধরন', describeEmergency: 'জরুরীর বর্ণনা দিন',
    sendAlert: 'জরুরী সতর্কতা পাঠান', alertCreated: 'সতর্কতা তৈরি হয়েছে', helpDispatched: 'সাহায্য পাঠানো হচ্ছে',
    medicalProfileLoaded: 'মেডিকেল প্রোফাইল স্বয়ংক্রিয়ভাবে লোড হয়েছে',
    noProfileFound: 'কোনো মেডিকেল প্রোফাইল পাওয়া যায়নি।', setOneUp: 'একটি সেটআপ করুন',
    fasterCare: 'দ্রুত জরুরী যত্নের জন্য।',
    profileSentToHospital: 'এই ডেটা স্বয়ংক্রিয়ভাবে হোটেল কর্মী এবং হাসপাতালে পাঠানো হবে।',
    hospitalPortal: 'হাসপাতাল জরুরী পোর্টাল', incomingPatients: 'আগত রোগী',
    acknowledgeAlert: 'সতর্কতা স্বীকার করুন', bedReady: 'বেড প্রস্তুত', patientArrived: 'রোগী এসেছে',
    assignBed: 'বেড বরাদ্দ করুন', assignResponder: 'রেসপন্ডার নিযুক্ত করুন',
    noIncomingAlerts: 'কোনো আগত রোগীর সতর্কতা নেই', icdCode: 'ICD-10 কোড', condition_label: 'অবস্থা',
    department: 'বিভাগ', bloodType: 'রক্তের ধরন', knownConditions: 'পরিচিত অবস্থা',
    medications: 'ওষুধ', preferredHospital: 'পছন্দের হাসপাতাল',
    welcomeBack: 'স্বাগত ফিরে', signIn: 'সাইন ইন', signUp: 'সাইন আপ',
    continueWithGoogle: 'Google দিয়ে চালিয়ে যান', or: 'বা',
    loading: 'লোড হচ্ছে...', save: 'সংরক্ষণ করুন', cancel: 'বাতিল করুন', close: 'বন্ধ করুন',
    back: 'পিছনে', next: 'পরবর্তী', submit: 'জমা দিন', refresh: 'রিফ্রেশ করুন',
    connected: 'সংযুক্ত', connecting: 'সংযুক্ত হচ্ছে...', error: 'ত্রুটি', success: 'সাফল্য',
  },

  bho: {
    dashboard: 'डैशबोर्ड', askAIDoctor: 'AI डॉक्टर से पूछीं', symptomChecker: 'लक्षण जाँचे वाला',
    medicineFinder: 'दवाई खोजे वाला', medicineScanner: 'दवाई स्कैनर', medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर', appointments: 'अपॉइंटमेंट', emergency: 'आपातकालीन',
    hospitals: 'अस्पताल', settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षण, दवाई, बेमारी के बारे में पूछीं...', onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'लगे के अस्पताल', viewAll: 'सब देखीं', selectLocation: 'जगह चुनीं',
    medicineInfo: 'दवाई के जानकारी', scanMedicine: 'दवाई स्कैन करीं',
    scanDescription: 'कौनो भी दवाई के तुरंत स्कैन करीं आउर जानकारी पाईं',
    aiDiagnosis: 'AI निदान सलाह', healthStats: 'स्वास्थ्य आँकड़ा', heartRate: 'दिल के धड़कन',
    bloodPressure: 'ब्लड प्रेशर', sugarLevel: 'शुगर लेवल', enterSymptoms: 'नीचे आपन लक्षण लिखीं',
    aiSuggestion: 'AI सलाह', possibleViral: 'वायरल इन्फेक्शन हो सकेला', condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलीं', usedFor: 'खातिर इस्तेमाल होला', dosage: 'खुराक', availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
    medicalProfile: 'मेडिकल प्रोफाइल', myMedicalProfile: 'हमार मेडिकल प्रोफाइल',
    personalInfo: 'निजी जानकारी', fullName: 'पूरा नाम', age: 'उमर', dateOfBirth: 'जनम के तारीख',
    gender: 'लिंग', bloodGroup: 'खून के ग्रुप', height: 'ऊँचाई (सेमी)', weight: 'वजन (किग्रा)',
    medicalConditions: 'चिकित्सा स्थिति', currentMedications: 'अभी के दवाई', allergies: 'एलर्जी',
    vitals: 'जीव संकेत', emergencyContact: 'आपातकालीन संपर्क', preferredHospitals: 'पसंदीदा अस्पताल',
    saveProfile: 'प्रोफाइल सहेजीं', profileSaved: 'प्रोफाइल सहेजाइल!', saving: 'सहेजात बा…',
    privateData: 'निजी — बस आपहीं के देखाई देला',
    profileAutoFills: 'प्रोफाइल सहेजाइल — SOS अलर्ट में आपने भराई',
    completeProfile: 'आपन मेडिकल प्रोफाइल पूरा करीं',
    organDonor: 'हम अंग दाता हईं', doctorNotes: 'डॉक्टर लोगन खातिर विशेष नोट',
    insurance: 'बीमा', hasInsurance: 'हमरे पास स्वास्थ्य बीमा बा', policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफाइल फोटो', uploadPhoto: 'फोटो अपलोड करीं',
    displayName: 'प्रदर्शन नाम', email: 'ईमेल', bio: 'परिचय', saveChanges: 'बदलाव सहेजीं',
    appearance: 'दिखावट', lightMode: 'उजियार', darkMode: 'अँधेरा', systemMode: 'सिस्टम',
    notifications: 'सूचना', privacy: 'गोपनीयता', signOut: 'साइन आउट',
    deleteAccount: 'खाता आउर डेटा मेटाईं',
    emergency_title: 'आपातकाल?', emergency_subtitle: 'फटाफट मदद एक टैप दूर बा।',
    reportEmergency: 'आपातकाल जानकारी दीं', yourName: 'आपन नाम', roomNo: 'कमरा नंबर', floor: 'मंजिल',
    emergencyType: 'आपातकाल के प्रकार', describeEmergency: 'आपातकाल के बारे में बताईं',
    sendAlert: 'आपातकाल अलर्ट भेजीं', alertCreated: 'अलर्ट बनाइल गइल', helpDispatched: 'मदद भेजात बा',
    medicalProfileLoaded: 'मेडिकल प्रोफाइल आपने लोड भइल',
    noProfileFound: 'कउनो मेडिकल प्रोफाइल ना मिलल।', setOneUp: 'एक बनाईं',
    fasterCare: 'तेज आपातकालीन देखभाल खातिर।',
    profileSentToHospital: 'ई डेटा होटल स्टाफ आउर अस्पताल के आपने भेजाई।',
    hospitalPortal: 'अस्पताल आपातकाल पोर्टल', incomingPatients: 'आवत रहे वाला मरीज',
    acknowledgeAlert: 'अलर्ट मान लीं', bedReady: 'बेड तैयार', patientArrived: 'मरीज आ गइल',
    assignBed: 'बेड दीं', assignResponder: 'रेस्पॉंडर नियुक्त करीं',
    noIncomingAlerts: 'कउनो आवत मरीज अलर्ट नइखे', icdCode: 'ICD-10 कोड', condition_label: 'स्थिति',
    department: 'विभाग', bloodType: 'खून के प्रकार', knownConditions: 'जानल स्थिति',
    medications: 'दवाई', preferredHospital: 'पसंदीदा अस्पताल',
    welcomeBack: 'फिर से स्वागत', signIn: 'साइन इन', signUp: 'साइन अप',
    continueWithGoogle: 'Google से जारी रखीं', or: 'या',
    loading: 'लोड होत बा...', save: 'सहेजीं', cancel: 'रद्द करीं', close: 'बंद करीं',
    back: 'पाछे', next: 'अगिला', submit: 'सबमिट करीं', refresh: 'रिफ्रेश करीं',
    connected: 'कनेक्टेड', connecting: 'कनेक्ट होत बा...', error: 'गलती', success: 'सफलता',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && LANGUAGES.some((l) => l.code === saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    window.dispatchEvent(new CustomEvent('language-changed', { detail: lang }));
  };

  const currentLangMeta = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const getLanguageInstruction = () => {
    if (language === 'en') return '';
    return `IMPORTANT: Write your ENTIRE response in ${currentLangMeta.name} (${currentLangMeta.native}) using native script. Do NOT reply in English unless writing specific medicine names.`;
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLangMeta, getLanguageInstruction }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    const defaultMeta = LANGUAGES[0];
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
      currentLangMeta: defaultMeta,
      getLanguageInstruction: () => '',
    };
  }
  return context;
}
